name: Deploy to EC2 and Restart Flask Service

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_ec2
        chmod 600 ~/.ssh/github_ec2
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Upload Flask code to EC2
      run: |
        ssh -i ~/.ssh/github_ec2 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          mkdir -p ~/flaskapp
          exit
        EOF
        scp -i ~/.ssh/github_ec2 -o StrictHostKeyChecking=no app.py requirements.txt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/flaskapp/

    - name: Restart Gunicorn via systemd
      run: |
        ssh -i ~/.ssh/github_ec2 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/flaskapp
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flaskapp.service
        EOF
