name: Deploy to EC2 with Gunicorn

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_ec2
        chmod 600 ~/.ssh/github_ec2
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/github_ec2 -o StrictHostKeyChecking=no app.py requirements.txt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/flaskapp/

    - name: Restart systemd service
      run: |
        ssh -i ~/.ssh/github_ec2 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/flaskapp
          pip3 install -r requirements.txt
          sudo systemctl restart flaskapp.service
        EOF
